data:
  data_dir: "MU-Glioma-Post/"
  batch_size: 32
  num_workers: 8
  persistent_workers: true
  pin_memory: true
  prefetch_factor: 3
  val_split: 0.3
  test_split: 0.1
  include_empty_masks: false

training:
  lr: 0.0005
  gamma: 0.98
  eps_start: 1.0
  eps_end: 0.02
  eps_decay: 300000
  memory_size: 50000
  target_update: 5000
  max_steps: 50
  grad_clip: 7.0
  lr_gamma: 0.98
  seed: 42
  val_interval: 1
  max_epochs: 50

environment:
  iou_threshold: 0.7

logging:
  log_dir: "lightning_logs"
  logger_name: "dqn_agent"
  checkpoint_dir: "checkpoints"
  test_gif_limit: 10
  test_gif_dir: "lightning_logs/test_gifs"
  test_gif_fps: 4
  early_stopping_patience: 10
