seed: 42
verbose: false

data:
  data_dir: "MU-Glioma-Post/"
  batch_size: 16
  num_workers: 8
  persistent_workers: true
  pin_memory: false
  prefetch_factor: 4
  val_split: 0.3
  test_split: 0.2
  include_empty_masks: false
  embedding_device: "mps"

encoder:
  name: "efficientnet_b0"
  pretrained: true
  trainable: false
  embedding_noise_std: 0.00

environment:
  num_sides: 32
  max_steps: 40
  iou_low_threshold: 0.2
  iou_high_threshold: 0.5
  initial_radius: 90.0
  line_distance_step_scale: 10.0
  line_angle_step_scale_deg: 10.0
  center_step_scale: 10.0
  line_max_angle_offset_deg: 45.0
  line_min_distance: 0.0
  line_max_distance_margin: 1.0
  iou_downsample: 4
  compute_vertices: true
  reward_success: 4.0
  reward_no_tumor: 2.0
  reward_false_stop: -3.0
  time_penalty: 0.02
  hold_penalty: 0.5

algorithm:
  gamma: 0.99
  n_step: 3
  tau: 0.005
  actor_lr: 0.001
  critic_lr: 0.001
  policy_delay: 2
  exploration_noise:
    sigma_init: 1.0
    sigma_final: 0.05
    steps: 500000
  target_policy_noise_std: 0.2
  target_policy_noise_clip: 0.5
  max_grad_norm: 10.0
  embedding_noise_std: 0.01
  embedding_projected_dim: 256
  pr_alpha: 0.6
  pr_beta_start: 0.4
  pr_beta_steps: 200000
  pr_eps: 1.0e-6
  actor_hidden_sizes: [256, 128]
  critic_hidden_sizes: [256, 128]
  replay_capacity: 300000
  # guidance_mode options: "critic_guidance", "true_guidance", "mixed", "true_guidance_post_noise", "random_true_guidance", "none"
  guidance_mode: "true_guidance"
  mixed_guidance_steps: 2000000  # number of environment interactions before switching to critic-guided actions
  guidance_schedule:
    scale_init: 1.0
    scale_final: 0.5
    steps: 2000000
  guided_actor_loss: true
  guided_actor_loss_weight: 2.0
  use_embedding_pointers: true
  actor_lr_schedule:
    lr_init: 0.001
    lr_final: 0.0001
    steps: 10  # number of epochs to reach lr_final
  critic_lr_schedule:
    lr_init: 0.001
    lr_final: 0.0001
    steps: 10

training:
  max_epochs: 40
  precision: "32-true"
  update_batch_size: 512
  update_every_n_steps: 8
  collect_steps_per_batch: 20
  warmup_steps: 1000
  log_interval: 10

logging:
  log_dir: "lightning_logs"
  logger_name: "td3_agent"
  checkpoint_dir: "checkpoints"
  test_gif_limit: 10
  test_gif_dir: "lightning_logs/test_gifs"
  test_gif_fps: 2
  early_stopping_patience: 20
