data:
  data_dir: "MU-Glioma-Post/"
  batch_size: 16
  num_workers: 8
  persistent_workers: true
  pin_memory: true
  prefetch_factor: 4
  val_split: 0.1
  test_split: 0.1
  include_empty_masks: false

training:
  lr: 0.0005
  gamma: 0.98
  eps_start: 1.0
  eps_end: 0.02
  eps_decay: 300000
  memory_size: 50000
  target_update: 5000
  max_steps: 50
  grad_clip: 7.0
  lr_gamma: 0.98
  seed: 42
  val_interval: 1
  max_epochs: 30
  
  # Action diversity parameters
  action_history_size: 5      # Size of action history buffer for tracking diversity
  movement_frequency: 3       # Force movement action every N zoom actions
  diversity_penalty: 0.1      # Penalty for repeating same action too frequently

environment:
  iou_threshold: 0.7
  centering_reward_weight: 0.5  # Weight for centering reward component

logging:
  log_dir: "lightning_logs"
  logger_name: "dqn_agent"
  checkpoint_dir: "checkpoints"
  test_gif_limit: 10
  test_gif_dir: "lightning_logs/test_gifs"
  test_gif_fps: 4
  early_stopping_patience: 20