data:
  data_dir: "MU-Glioma-Post/"
  batch_size: 32
  num_workers: 8
  persistent_workers: true
  pin_memory: false
  prefetch_factor: 3
  val_split: 0.3
  test_split: 0.1
  include_empty_masks: false

training:
  lr: 0.0005
  gamma: 0.98
  eps_start: 1.0
  eps_end: 0.02
  eps_decay: 300000
  memory_size: 50000
  target_update: 5000
  max_steps: 50
  grad_clip: 7.0
  lr_gamma: 0.98
  seed: 42
  val_interval: 1
  max_epochs: 40
  precision: "32-true"

environment:
  iou_threshold: 0.7
  initial_mode: random_corners
  step_size: 10.0
  scale_factor: 1.1
  min_bbox_size: 10.0
  initial_margin: 8.0
  reward_clip_range: [-10.0, 10.0]
  delta_iou: 2.5
  current_iou: 0.5
  stop_reward_success: 10.0
  stop_reward_no_tumor: 10.0
  stop_reward_false: 1.0
  time_penalty: 0.02
  hold_penalty: 0.0

logging:
  log_dir: "lightning_logs"
  logger_name: "dqn_agent"
  checkpoint_dir: "checkpoints"
  test_gif_limit: 10
  test_gif_dir: "lightning_logs/test_gifs"
  test_gif_fps: 4
  early_stopping_patience: 20
